"""empty message

Revision ID: 29fd3e62ede2
Revises: b0aadd52c5b1
Create Date: 2024-04-12 17:04:00.425170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fd3e62ede2'
down_revision = 'b0aadd52c5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_winned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('matches_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('matches_winned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('matches_winned')
        batch_op.drop_column('matches_played')
        batch_op.drop_column('games_winned')
        batch_op.drop_column('games_played')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
