"""empty message

Revision ID: b0aadd52c5b1
Revises: f2dce2b3ecd0
Create Date: 2024-04-12 13:31:23.345252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0aadd52c5b1'
down_revision = 'f2dce2b3ecd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('is_finished')
        batch_op.drop_column('current_round')

    # ### end Alembic commands ###
