"""empty message

Revision ID: f78fa9c779a3
Revises: 4a3ae7c87f2c
Create Date: 2024-04-17 15:04:55.191365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78fa9c779a3'
down_revision = '4a3ae7c87f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('player2_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('player2_name')
        batch_op.drop_column('player1_name')

    # ### end Alembic commands ###
